### ISSUE TITLE
Processor for specific handler only

### ISSUE THREAD

**Issue by JanMikes** [contributte/monolog#12]
Hi!

We need add processor for specific handler only. 

In our case it is Sentry handler and processor specific only for it, not suitable for other handlers.

I was inspired by https://symfony.com/doc/current/logging/processors.html#registering-processors-per-handler

**Comment by mabar** [comment]
I was thinking about it and it's currently not a blocking issue, because everything could be configured via setup. I am too busy to implement non-critical features so I am closing for now. Feel free to open PR if willing to implement it.

**Comment by JanMikes** [comment]
Sure Thing! I just wonder what is purpose of closing issue when single person is not able to implement it due to not enough time. 

You can use labels, some combination of "low prio", "non-blocking", "help wanted". Anything just to keep it tracked and if someone goes around, he can pick it, though im fine with that, it is up to you as maintainer 😉.
