### ISSUE TITLE
Is there an easy way to set up Monolog Formatter? (escaping % in config)

### ISSUE THREAD

**Issue by matronator** [contributte/monolog#16]
<del>I see no mention of it in the docs. I tried setting it in the config like handlers and processors are set-up, but seems like `formatters` is not an option. Is there some easy way to change the default formatter to the NormalizerFormatter?</del>

Nevermind, figured it out in config.neon, but I came across a different problem.

When I want to set the formatter parameters, there seems to be no way of escaping the `%` symbol. The Nette docs says to put another `%` before it to escape, but it still tries to parse it as a parameter.

```
setFormatter(Monolog\Formatter\LineFormatter('%%[datetime]%% %%message%% %%context%%', 'Y-m-d H:i:s', false, true)
```

Results in:

```
Nette\InvalidArgumentException
Missing parameter 'datetime'.
```

**Comment by mabar** [comment]
Yeah, we should definitely add example in docs
Problem with percents escaping is caused by doubled parameters resolution done by Nette. I am not sure, if we can fix that issue (definitely not without BC break)
Workaround is - double the doubled percents :'D `%%%%` should work

**Comment by matronator** [comment]
Escaping the escaping, lol :D . But it does the trick, thank you! :)
