### ISSUE TITLE
Odkaz na composer v read-me je fishing

### ISSUE THREAD

**Issue by VojtechBuba** [contributte/monolog#26]
Nevím jestli to je schválně, ale v readme na hlavní straně je odkaz na composer a jedná se o špatný odkaz, který vede na stránku .com místo .org. Tento odkaz je docela propracovaný fishing, pokud to není záměr tak bych navrhoval odkaz opravit :)

**Comment by petrparolek** [comment]
Pošlu do všech repozitářů pull requesty

**Comment by f3l1x** [comment]
Dobrej catch. Diky. Zamer to neni. Spis unava. :-D

**Comment by petrparolek** [comment]
> Dobrej catch. Diky. Zamer to neni. Spis unava. :-D

Měl jsem dojem, že jsem už kontroloval a opravoval! Ale asi jen contributte web

**Comment by petrparolek** [comment]
@f3l1x hotovo, prosím, co nejdřív to všechno začleň. Potom bychom měli ještě jednou u všech repozitářů včetně zaarchivovaných zkontrolovat odkazy

**Comment by f3l1x** [comment]
Snad osetreno vsude. Diky @VojtechBuba za report.
