### ISSUE TITLE
TracyProcessor

### ISSUE THREAD

**Issue by mabar** [contributte/monolog#4]
Get exception from context and create tracy bluescreen for it.

Some kind of storage would be nice, so user is not forced to use local filesystem. (same for #3)

**Comment by JanTvrdik** [comment]
> Get exception from context and create tracy bluescreen for it.

This can be done with `Tracy\Bridges\Psr\TracyToPsrLoggerAdapter`. See https://github.com/contributte/monolog/issues/6

> Some kind of storage would be nice, so user is not forced to use local filesystem. (same for #3)

This can be done with https://github.com/mangoweb-backend/monolog-tracy-handler.

**Comment by mabar** [comment]
monolog-tracy-handler requires bluescreen to be physically available in local filesystem, am I right? I would also like to support read-only deployments and configurations which don't use default Tracy\Logger at all, so I would prefer this approach
```php
$bs = new BlueScreen();
ob_start();
$bs->renderToFile($exception, 'php://temp');
$contents = ob_get_contents();
```

**Comment by JanTvrdik** [comment]
Without writing to local filesystem you loose the built-in de-duplication (i.e. single error on a popular site can generate many GB of data) and also you need more memory.

**Comment by mabar** [comment]
You are right, better drop bluescreens completely for read-only deployments.
