### ISSUE TITLE
How to configure handler for Symfony Console

### ISSUE THREAD

**Issue by foxycode** [contributte/monolog#7]
Class `Symfony\Component\Console\Logger\ConsoleLogger` extends from `Psr\Log\AbstractLogger` and wants `OutputInterface` in constructor. Because of that, It is impossible to add console channel.

Is there any solution? If yes, can you add example to documentation?

**Comment by mabar** [comment]
Imho [this](https://github.com/symfony/monolog-bridge/blob/master/Handler/ConsoleHandler.php) is what you want

**Comment by foxycode** [comment]
@mabar It isn't It still have `OutputInterface` in constructur, I can't register it using your extension. Monolog config in Symfony works different way, it doesn't need to instantiate class right away when adding channel.

**Comment by mabar** [comment]
It also have event to set output https://github.com/symfony/monolog-bridge/blob/master/Handler/ConsoleHandler.php#L114

**Comment by foxycode** [comment]
@mabar This could work for me. Thanks.
